test: 🧪  Add unit tests to validate directory mapping and existence of game folder  (#49)
#minor

diff --git a/.github/workflows/beta.yml b/.github/workflows/beta.yml
--- a/.github/workflows/beta.yml
+++ b/.github/workflows/beta.yml
@@ -83,6 +83,60 @@ jobs:
             IMAGE=jives/hlds:${{ matrix.game }}-beta
             VERSION=beta
 
+      - name: Add Custom Mod Content 📂
+        run: |
+          mkdir -p ./mods/decay
+          touch ./mods/decay/plugin.ini
+
+      - name: Add Configuration 📂
+        run: |
+          mkdir -p ./config
+          touch ./config/test.cfg
+
+      - name: Run Docker Container 🐳
+        run: |
+          docker run -d -ti \
+            --name hlds \
+            -v "./config:/temp/config" \
+            -v "./mods:/temp/mods" \
+            -p 27015:27015/udp \
+            -p 27015:27015 \
+            -p 26900:26900/udp \
+            -e GAME=${GAME} \
+            jives/hlds:${{ env.GAME }}-beta  \
+            "+log on +rcon_password changeme +maxplayers 12"
+          sleep 5
+
+      - name: Validate Directory Mappings 📂
+        run: |
+          # Check if plugin.ini exists in the decay directory
+          if [ "$(docker exec hlds ls /opt/steam/hlds/decay | grep -c 'plugin.ini')" -eq 0 ]; then
+            echo "plugin.ini file is missing in the decay directory!"
+            exit 1
+          fi
+
+          # Check if test.cfg exists in the game directory
+          if [ "$(docker exec hlds ls /opt/steam/hlds/${{ env.GAME }} | grep -c 'test.cfg')" -eq 0 ]; then
+            echo "test.cfg file is missing in the ${{ env.GAME }} directory!"
+            exit 1
+          fi
+
+          # Check if crazytank.bsp exists in the maps directory
+          if [ "$(docker exec hlds ls /opt/steam/hlds/${{ env.GAME }}/maps | grep -c 'crazytank.bsp')" -eq 0 ]; then
+            echo "crazytank.bsp file is missing in the maps directory!"
+            exit 1
+          fi
+
+          echo "Volume mappings work as expectected!"
+
+      - name: Validate Game Directory Is Present 📂
+        run: |
+          GAME_NAME=$(echo "${{ env.GAME }}" | sed 's/-legacy//')
+          if [ "$(docker exec hlds ls /opt/steam/hlds | grep -c "$GAME_NAME")" -eq 0 ]; then
+            echo "$GAME_NAME directory is missing!"
+            exit 1
+          fi
+
       - name: Set repo owner to lowercase
         id: repo_owner
         run: echo "::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')"
@@ -103,3 +157,10 @@ jobs:
             FLAG=${{ env.FLAG }}
             VERSION=beta
             IMAGE=ghcr.io/${{ steps.repo_owner.outputs.repo_owner }}/hlds:${{ matrix.game }}-beta
+
+      - name: Cleanup 🧹
+        if: always()
+        run: |
+          docker stop hlds
+          docker rm hlds
+          docker system prune --all --force
