fix: add

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -41,7 +41,9 @@ jobs:
       - name: Add Configuration 📂
         run: |
           mkdir -p ./config
+          mkdir -p ./config/maps
           touch ./config/test.cfg
+          touch ./config/maps/crazytank.bsp
 
       - name: Run Docker Container 🐳
         run: |
@@ -67,6 +69,12 @@ jobs:
           # Check if test.cfg exists in the game directory
           if [ "$(docker exec hlds ls /opt/steam/hlds/${{ env.GAME }} | grep -c 'test.cfg')" -eq 0 ]; then
             echo "test.cfg file is missing in the ${{ env.GAME }} directory!"
+            exit 1
+          fi
+
+          # Check if crazytank.bsp exists in the maps directory
+          if [ "$(docker exec hlds ls /opt/steam/hlds/${{ env.GAME }}/maps | grep -c 'crazytank.bsp')" -eq 0 ]; then
+            echo "crazytank.bsp file is missing in the maps directory!"
             exit 1
           fi
 
